FROM postgres:11.4-alpine

# For more information check https://hub.docker.com/_/postgres and
# https://docs.docker.com/samples/library/postgres/

USER postgres

# shm
# logs
# data
# get port from postgres Dockerfile
# connect django