language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install -y ncbi-blast+ mafft
install:
  - "pip install -r requirements.txt"
script:
  - "pytest --cov-report=xml --cov=cathapi --cov=frontend --cov=select_template_api frontend/tests.py select_template_api/tests.py"
after_success:
  - codecov