language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install -y ncbi-blast+ mafft
install:
  - "pip install -r requirements.txt"
script:
  - "pytest --cov=cathapi"
after_success:
  - codecov