# Generated by Django 2.0.7 on 2018-07-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecttemplatetask',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
