# Generated by Django 2.0.7 on 2018-07-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180731_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecttemplatetask',
            name='task_id',
        ),
    ]
