# Generated by Django 2.1.2 on 2018-10-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_selecttemplatetask_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecttemplatetask',
            old_name='fasta',
            new_name='query_sequence',
        ),
        migrations.AddField(
            model_name='selecttemplatetask',
            name='query_id',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
