# Generated by Django 2.1.2 on 2018-10-25 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181024_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecttemplatetask',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
