# Generated by Django 2.1.2 on 2018-10-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_selecttemplatetask_remote_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecttemplatetask',
            old_name='ip',
            new_name='client_ip',
        ),
    ]
