# Generated by Django 2.1.2 on 2018-11-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181025_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecttemplatetask',
            name='results',
        ),
        migrations.AddField(
            model_name='selecttemplatetask',
            name='results_csv',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='selecttemplatetask',
            name='results_json',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='selecttemplatetask',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('queued', 'queued'), ('running', 'running'), ('error', 'error'), ('success', 'success')], default='unknown', max_length=10),
        ),
    ]
