# Generated by Django 2.2.1 on 2019-05-07 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectTemplateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('query_id', models.CharField(max_length=50)),
                ('query_sequence', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('unknown', 'unknown'), ('queued', 'queued'), ('running', 'running'), ('error', 'error'), ('success', 'success')], default='unknown', max_length=10)),
                ('message', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('results_json', models.CharField(blank=True, max_length=100000)),
                ('client_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('remote_task_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
