# Generated by Django 2.2.1 on 2019-05-09 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('select_template_api', '0002_selecttemplatehit'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecttemplatehit',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
