# Generated by Django 2.2.1 on 2019-05-30 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('select_template_api', '0003_selecttemplatehit_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectTemplateAlignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hit_uuid', models.UUIDField(editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('align_method', models.CharField(choices=[('unknown', 'unknown'), ('queued', 'queued'), ('running', 'running'), ('error', 'error'), ('success', 'success')], default='mafft', max_length=20)),
                ('pdb_id', models.CharField(max_length=4)),
                ('auth_asym_id', models.CharField(max_length=4)),
                ('template_sequence', models.CharField(max_length=2000)),
                ('template_seqres_offset', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SelectTemplateHits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('task_uuid', models.UUIDField(editable=False)),
                ('query_range', models.CharField(max_length=100)),
                ('query_range_sequence', models.CharField(max_length=5000)),
                ('funfam_id', models.CharField(max_length=100)),
                ('funfam_name', models.CharField(max_length=500)),
                ('is_resolved_hit', models.BooleanField(default=False)),
                ('has_structure', models.BooleanField(null=True)),
                ('ec_count', models.IntegerField(null=True)),
                ('go_count', models.IntegerField(null=True)),
                ('seq_count', models.IntegerField(null=True)),
                ('dops_score', models.IntegerField(null=True)),
                ('evalue', models.FloatField(null=True)),
                ('bitscore', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectTemplateTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('query_id', models.CharField(max_length=50)),
                ('query_sequence', models.CharField(max_length=2000)),
                ('status', models.CharField(default='unknown', max_length=10)),
                ('message', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('results_json', models.CharField(blank=True, max_length=100000)),
                ('client_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('remote_task_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SelectTemplateHit',
        ),
        migrations.DeleteModel(
            name='SelectTemplateTask',
        ),
    ]
