# Generated by Django 2.2.1 on 2019-05-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_template_api', '0004_auto_20190530_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecttemplatehits',
            old_name='dops_score',
            new_name='ff_dops_score',
        ),
        migrations.RenameField(
            model_name='selecttemplatehits',
            old_name='funfam_id',
            new_name='ff_id',
        ),
        migrations.RenameField(
            model_name='selecttemplatehits',
            old_name='funfam_name',
            new_name='ff_name',
        ),
        migrations.RenameField(
            model_name='selecttemplatehits',
            old_name='seq_count',
            new_name='ff_seq_count',
        ),
        migrations.RenameField(
            model_name='selecttemplatehits',
            old_name='ec_count',
            new_name='ff_uniq_ec_count',
        ),
        migrations.RenameField(
            model_name='selecttemplatehits',
            old_name='go_count',
            new_name='ff_uniq_go_count',
        ),
        migrations.RemoveField(
            model_name='selecttemplatehits',
            name='has_structure',
        ),
        migrations.AddField(
            model_name='selecttemplatehits',
            name='ff_cath_domain_count',
            field=models.BooleanField(null=True),
        ),
    ]
