# Generated by Django 2.2.1 on 2019-05-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_template_api', '0005_auto_20190530_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectTemplateAlignments',
            new_name='SelectTemplateAlignment',
        ),
        migrations.RenameModel(
            old_name='SelectTemplateHits',
            new_name='SelectTemplateHit',
        ),
        migrations.RenameModel(
            old_name='SelectTemplateTasks',
            new_name='SelectTemplateTask',
        ),
    ]
