# Generated by Django 2.2.1 on 2019-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_template_api', '0006_auto_20190530_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecttemplatealignment',
            name='align_method',
            field=models.CharField(choices=[('mafft', 'mafft')], default='mafft', max_length=20),
        ),
        migrations.AlterField(
            model_name='selecttemplatetask',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('queued', 'queued'), ('running', 'running'), ('error', 'error'), ('success', 'success')], default='unknown', max_length=10),
        ),
    ]
