# Generated by Django 2.2.1 on 2019-06-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_template_api', '0007_auto_20190606_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecttemplatehit',
            name='ff_cath_domain_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selecttemplatetask',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
